// ISO 639-3 language codes (NOTE: this is a partial list, for franc language detector)
// -- Japanese names are taken from JISX0412-2
// -- Japanese names for macro-languages are taken from Wikipedia
// -- see also: https://www.asahi-net.or.jp/~ax2s-kmtn/ref/iso639.html
export const languageNames: Record<string, string> = {
  cmn: "中国語（官話）", //"Mandarin Chinese",
  spa: "スペイン語",
  eng: "英語",
  rus: "ロシア語",
  arb: "標準アラビア語", // "Standard Arabic",
  ben: "ベンガル語",
  hin: "ヒンディー語",
  por: "ポルトガル語",
  ind: "インドネシア語",
  jpn: "日本語",
  fra: "フランス語",
  deu: "ドイツ語",
  jav: "ジャワ語",
  kor: "韓国語",
  tel: "テルグ語",
  vie: "ベトナム語",
  mar: "マラーティー語",
  ita: "イタリア語",
  tam: "タミル語",
  tur: "トルコ語",
  urd: "ウルドゥー語",
  guj: "グジャラート語",
  pol: "ポーランド語",
  ukr: "ウクライナ語",
  kan: "カンナダ語",
  mai: "マイティリー語",
  mal: "マラヤーラム語",
  pes: "イラン・ペルシャ語", // "Iranian Persian",
  mya: "ビルマ語",
  swh: "スワヒリ語", // "Swahili",
  sun: "スンダ語",
  ron: "ルーマニア語",
  pan: "パンジャーブ語",
  bho: "ボージュプリー語",
  amh: "アムハラ語",
  hau: "ハウサ語",
  fuv: "ナイジェリアン・フルフルディ語", // "Nigerian Fulfulde",
  bos: "ボスニア語",
  hrv: "クロアチア語",
  nld: "オランダ語",
  srp: "セルビア語",
  tha: "タイ語",
  ckb: "ソラン語", // "Central Kurdish",
  yor: "ヨルバ語",
  uzn: "ウズベク語（北部方言）", // "Northern Uzbek",
  zlm: "マレー語", // "Malay",
  ibo: "イグボ語",
  npi: "ネパール語", // "Nepali",
  ceb: "セブアノ語",
  skr: "サライキ語", // "Saraiki",
  tgl: "タガログ語",
  hun: "ハンガリー語",
  azj: "北アゼルバイジャン語", // "North Azerbaijani",
  sin: "シンハラ語",
  koi: "コミ・ペルミャク語", // "Komi-Permyak",
  ell: "現代ギリシア語",
  ces: "チェコ語",
  mag: "マガヒー語",
  run: "ルンディ語",
  bel: "白ロシア語",
  plt: "プラトー・マダガスカル語", // "Plateau Malagasy",
  qug: "チンボラソ高地ケチュア語", // "Chimborazo Highland Quichua",
  mad: "マドゥラ語",
  nya: "チェワ語",
  zyb: "邕北チワン語", // "Yongbei Zhuang",
  pbu: "北部パシュトー語", // "Northern Pashto",
  kin: "ルワンダ語",
  zul: "ズールー語",
  bul: "ブルガリア語",
  swe: "スウェーデン語",
  lin: "リンガラ語",
  som: "ソマリ語",
  hms: "南部黔東苗語", // "Southern Qiandong Miao",
  hnj: "綠苗語", // "Hmong Njua",
  ilo: "イロカノ語",
  kaz: "カザフ語",
  uig: "ウイグル語",
  hat: "ハイチ語",
  khm: "カンボジア語",
  prs: "ダリー語", // "Dari",
  hil: "ヒリガイノン語",
  sna: "ショナ語",
  tat: "タタール語",
  xho: "コサ語",
  hye: "アルメニア語",
  min: "ミナンカバウ語",
  afr: "アフリカーンス語",
  lua: "ルバ・ルルア小語群",
  sat: "サンタール語",
  bod: "チベット語",
  tir: "ティグリニア語",
  fin: "フィンランド語",
  slk: "スロバキア語",
  tuk: "トルクメン語",
  dan: "デンマーク語",
  nob: "ブークモール",
  suk: "スクマ語",
  als: "トスク・アルバニア語", // "Tosk Albanian",
  sag: "サンゴ語",
  nno: "ニューノシュク",
  heb: "ヘブライ語",
  mos: "モシ語",
  tgk: "タジク語",
  cat: "カタロニア語",
  sot: "南ソト語",
  kat: "グルジア語",
  bcl: "中央ビコール語", // "Central Bikol",
  glg: "ガリシア語",
  lao: "ラオ語",
  lit: "リトアニア語",
  umb: "ウンブンドゥ語",
  tsn: "ツワナ語",
  vec: "ヴェネト語", // "Venetian",
  nso: "北ソト語",
  ban: "バリ語",
  bug: "ブギス語",
  knc: "中央カヌリ語", // "Central Kanuri",
  kng: "コンゴ語", // "Koongo",
  ibb: "イビビオ語", // "Ibibio",
  lug: "ガンダ語",
  ace: "アチェ語",
  bam: "バンバラ語",
  tzm: "中央アトラス・タマジクト語", // "Central Atlas Tamazight",
  ydd: "東イディッシュ語", // "Eastern Yiddish",
  kmb: "キンブンドゥ語",
  lun: "ルンダ語",
  shn: "シャン語",
  war: "ワライ語",
  dyu: "ジュラ語",
  wol: "ウォロフ語",
  kir: "キルギス語",
  nds: "低地ドイツ語",
  fuf: "プラー語", // "Pular",
  mkd: "マケドニア語",
  vmw: "マクア語", // "Makhuwa",
  zgh: "標準モロッコ・タマジクト語", // "Standard Moroccan Tamazight",
  ewe: "エウェ語群",
  khk: "モンゴル語（ハルハ方言）", // "Halh Mongolian",
  slv: "スロベニア語",
  ayr: "中央アイマラ語", // "Central Aymara",
  bem: "ベンバ語",
  emk: "北部マニンカ語", // "Eastern Maninkakan",
  bci: "バウレ語", // "Baoulé",
  bum: "ブル語", // "Bulu",
  epo: "エスペラント語",
  pam: "カパンパンガン語",
  tiv: "ティブ語",
  tpi: "トク・ピシン",
  ven: "ベンダ語",
  ssw: "スワティ語",
  nyn: "ニャンコレ語",
  kbd: "カバルド語",
  iii: "彝語",
  yao: "ヤオ語",
  lvs: "標準ラトビア語", // "Standard Latvian",
  quz: "クスコ・ケチュア語", // "Cusco Quechua",
  src: "ログドーロ・サルデーニャ語", // "Logudorese Sardinian",
  rup: "アルーマニア語",
  sco: "低地スコットランド・ゲール語",
  tso: "ツォンガ語",
  men: "メンデ語",
  fon: "フォン語",
  nhn: "中央ナワトル語", // "Central Nahuatl",
  dip: "北東部ディンカ語", // "Northeastern Dinka",
  kde: "マコンデ語", // "Makonde",
  kbp: "カビエ語", // "Kabiyè",
  tem: "テムネ語",
  toi: "トンガ語（ザンビア）", // "Tonga",
  ekk: "標準エストニア語", // "Standard Estonian",
  snk: "ソニンケ語",
  cjk: "チョクウェ語", // "Chokwe",
  ada: "アダグメ語",
  aii: "アッシリア現代アラム語", // "Assyrian Neo-Aramaic",
  quy: "アヤクーチョ・ケチュア語", // "Ayacucho Quechua",
  rmn: "バルカン・ロマ語", // "Balkan Romani",
  bin: "ビニ語",
  gaa: "ガー語",
  ndo: "ンドゥンガ語"
};
