// ISO 639-3 language codes (NOTE: this is a partial list, for franc language detector)
// -- Japanese names are taken from JISX0412-2
// -- ref: https://www.asahi-net.or.jp/~ax2s-kmtn/ref/iso639.html
export const languageNames: Record<string, string> = {
  cmn: "Mandarin Chinese",
  spa: "スペイン語",
  eng: "英語",
  rus: "ロシア語",
  arb: "Standard Arabic",
  ben: "ベンガル語",
  hin: "ヒンディー語",
  por: "ポルトガル語",
  ind: "インドネシア語",
  jpn: "日本語",
  fra: "フランス語",
  deu: "ドイツ語",
  jav: "ジャワ語",
  kor: "韓国語",
  tel: "テルグ語",
  vie: "ベトナム語",
  mar: "マラーティー語",
  ita: "イタリア語",
  tam: "タミル語",
  tur: "トルコ語",
  urd: "ウルドゥー語",
  guj: "グジャラート語",
  pol: "ポーランド語",
  ukr: "ウクライナ語",
  kan: "カンナダ語",
  mai: "マイティリー語",
  mal: "マラヤーラム語",
  pes: "Iranian Persian",
  mya: "ビルマ語",
  swh: "Swahili",
  sun: "スンダ語",
  ron: "ルーマニア語",
  pan: "パンジャーブ語",
  bho: "ボージュプリー語",
  amh: "アムハラ語",
  hau: "ハウサ語",
  fuv: "Nigerian Fulfulde",
  bos: "ボスニア語",
  hrv: "クロアチア語",
  nld: "オランダ語",
  srp: "セルビア語",
  tha: "タイ語",
  ckb: "Central Kurdish",
  yor: "ヨルバ語",
  uzn: "Northern Uzbek",
  zlm: "Malay",
  ibo: "イグボ語",
  npi: "Nepali",
  ceb: "セブアノ語",
  skr: "Saraiki",
  tgl: "タガログ語",
  hun: "ハンガリー語",
  azj: "North Azerbaijani",
  sin: "シンハラ語",
  koi: "Komi-Permyak",
  ell: "現代ギリシア語",
  ces: "チェコ語",
  mag: "マガヒー語",
  run: "ルンディ語",
  bel: "白ロシア語",
  plt: "Plateau Malagasy",
  qug: "Chimborazo Highland Quichua",
  mad: "マドゥラ語",
  nya: "チェワ語",
  zyb: "Yongbei Zhuang",
  pbu: "Northern Pashto",
  kin: "ルワンダ語",
  zul: "ズールー語",
  bul: "ブルガリア語",
  swe: "スウェーデン語",
  lin: "リンガラ語",
  som: "ソマリ語",
  hms: "Southern Qiandong Miao",
  hnj: "Hmong Njua",
  ilo: "イロカノ語",
  kaz: "カザフ語",
  uig: "ウイグル語",
  hat: "ハイチ語",
  khm: "カンボジア語",
  prs: "Dari",
  hil: "ヒリガイノン語",
  sna: "ショナ語",
  tat: "タタール語",
  xho: "コサ語",
  hye: "アルメニア語",
  min: "ミナンカバウ語",
  afr: "アフリカーンス語",
  lua: "ルバ・ルルア小語群",
  sat: "サンタール語",
  bod: "チベット語",
  tir: "ティグリニア語",
  fin: "フィンランド語",
  slk: "スロバキア語",
  tuk: "トルクメン語",
  dan: "デンマーク語",
  nob: "ブークモール",
  suk: "スクマ語",
  als: "Tosk Albanian",
  sag: "サンゴ語",
  nno: "ニューノシュク",
  heb: "ヘブライ語",
  mos: "モシ語",
  tgk: "タジク語",
  cat: "カタロニア語",
  sot: "南ソト語",
  kat: "グルジア語",
  bcl: "Central Bikol",
  glg: "ガリシア語",
  lao: "ラオ語",
  lit: "リトアニア語",
  umb: "ウンブンドゥ語",
  tsn: "ツワナ語",
  vec: "Venetian",
  nso: "北ソト語",
  ban: "バリ語",
  bug: "ブギス語",
  knc: "Central Kanuri",
  kng: "Koongo",
  ibb: "Ibibio",
  lug: "ガンダ語",
  ace: "アチェ語",
  bam: "バンバラ語",
  tzm: "Central Atlas Tamazight",
  ydd: "Eastern Yiddish",
  kmb: "キンブンドゥ語",
  lun: "ルンダ語",
  shn: "シャン語",
  war: "ワライ語",
  dyu: "ジュラ語",
  wol: "ウォロフ語",
  kir: "キルギス語",
  nds: "低地ドイツ語",
  fuf: "Pular",
  mkd: "マケドニア語",
  vmw: "Makhuwa",
  zgh: "Standard Moroccan Tamazight",
  ewe: "エウェ語群",
  khk: "Halh Mongolian",
  slv: "スロベニア語",
  ayr: "Central Aymara",
  bem: "ベンバ語",
  emk: "Eastern Maninkakan",
  bci: "Baoulé",
  bum: "Bulu",
  epo: "エスペラント語",
  pam: "カパンパンガン語",
  tiv: "ティブ語",
  tpi: "トク・ピシン",
  ven: "ベンダ語",
  ssw: "スワティ語",
  nyn: "ニャンコレ語",
  kbd: "カバルド語",
  iii: "彝語",
  yao: "ヤオ語",
  lvs: "Standard Latvian",
  quz: "Cusco Quechua",
  src: "Logudorese Sardinian",
  rup: "アルーマニア語",
  sco: "低地スコットランド・ゲール語",
  tso: "ツォンガ語",
  men: "メンデ語",
  fon: "フォン語",
  nhn: "Central Nahuatl",
  dip: "Northeastern Dinka",
  kde: "Makonde",
  kbp: "Kabiyè",
  tem: "テムネ語",
  toi: "Tonga",
  ekk: "Standard Estonian",
  snk: "ソニンケ語",
  cjk: "Chokwe",
  ada: "アダグメ語",
  aii: "Assyrian Neo-Aramaic",
  quy: "Ayacucho Quechua",
  rmn: "Balkan Romani",
  bin: "ビニ語",
  gaa: "ガー語",
  ndo: "ンドゥンガ語"
};
