import { signal, computed } from "@preact/signals";
import { useMemo, useEffect } from "preact/hooks";
import { gensym } from "./utils/gensym";
import { analyzerCategories, analyzers } from "./modules/analyzers";
import { importers } from "./modules/importers";
import { genInspector } from "./modules/inspector";
import { DataViewer } from "./DataViewer";
import { textData, type Data } from "./datatypes";
import type { AnalyzerModule, StateReporter } from "./modules";

/* ---- STATE */

type StackFrame = {
  // An unique id, generated by "gensym" util.
  id: number,
  // Latest output from the module. Updated by "stateReporter" fn defined later.
  // Note that only the frame on top of the stack can be updated.
  output: Data | null,
  module: AnalyzerModule,
};

const busy = signal(false);
const stack = signal<StackFrame[]>([]);

const stateReporterForId = (id: number): StateReporter => (state) => {
  const _stack = stack.peek(); // do not subscribe, to avoid infinite loops
  // If the frame is no longer active, do nothing.
  // This may occur when stateReporter is called from an async analyzer.
  if (id === _stack[_stack.length - 1]?.id) {
    busy.value = !!state.busy;
    if (state.output) {
      stack.value = [
        ..._stack.slice(0, -1),
        { ..._stack[_stack.length - 1], output: state.output },
      ];
    }
  }
};

// List of suggestions for the last output.
const suggestions = computed<{ reason: string, module: AnalyzerModule }[]>(() => {
  const suspicious = stack.value[stack.value.length - 1]?.output;
  if (suspicious) {
    return analyzers.map(analyzer => {
      const reason = analyzer.detect?.(suspicious) ?? null;
      if (reason) {
        return { reason, module: analyzer };
      }
      return null;
    }).filter(suggestion => !!suggestion);
  }
  return [];
});

// Initialize an analyzer and push on to the stack.
const pushAnalyzer = (module: AnalyzerModule) => {
  const _stack = stack.peek(); // do not subscribe, to avoid infinite loops
  busy.value = false;
  stack.value = [..._stack, { id: gensym(), module, output: null }];
};

// Inspect a single element in a MultipleData.
const inspect = (ix: number) => {
  const _stack = stack.peek(); // do not subscribe, to avoid infinite loops
  busy.value = false;
  stack.value = [..._stack, { id: gensym(), module: genInspector(ix), output: null }];
};

// Rollback to undo N-th frame (= activate "N-1"-th frame)
const rollback = (n: number) => {
  const _stack = stack.peek(); // do not subscribe, to avoid infinite loops
  busy.value = false;
  stack.value = _stack.slice(0, n);
};

/* ---- UI */

const AnalyzersList = () => (
  <section>
    <details>
      <summary>実装されている変換器・解析器</summary>
      {analyzerCategories.map(category => (
        <div key={category.category}>
          <b>{category.category}</b>
          <div style={{ marginLeft: "16px", fontSize: "smaller" }}>
            {category.analyzers.map((analyzer, ix) => (
              <>
                {ix > 0 ? "、" : ""}
                {analyzer.app ? (
                  <a key={analyzer.label} href={analyzer.app}>{analyzer.label}</a>
                ) : (
                  analyzer.label
                )}
              </>
            ))}
          </div>
        </div>
      ))}
      <div>
        <b>その他</b>
        <div style={{ marginLeft: "16px" }}>
          <small>ファイル形式の自動判別、条件に一致する単語や地名の特定</small>
        </div>
      </div>
    </details>
  </section>
);

const ImporterSelector = () => (
  stack.value.length === 0 ? (
    <section>
      <hr />
      <h3>モードを選ぶ：</h3>
      {importers.map(module => (
        <>
          <button
              key={module.label}
              type="button"
              onClick={() => pushAnalyzer(module)}>
            {module.label}
          </button>
          {"　"}
        </>
      ))}
    </section>
  ) : (
    <section>
      <p>
        <button type="button" onClick={() => rollback(0)}>
          最初に戻る
        </button>
      </p>
    </section>
  )
);

const Frame = ({ frame, ix }: { frame: StackFrame, ix: number }) => {
  const Component = frame.module.component;
  const input = stack.value[ix - 1]?.output ?? null;

  const isActive = ix === stack.value.length - 1;
  const isBusy = isActive && busy.value;

  const onUpdate = useMemo(() => stateReporterForId(frame.id), [frame.id]);
  const onInspect = isActive ? inspect : undefined;

  return (
    <section key={frame.id}>
      <hr />
      <h3>{frame.module.label}</h3>
      {frame.module.description ?? null}
      {/* render inactive (hidden) components too, to keep their state */}
      <div style={isActive ? { marginBottom: "1em" } : { display: "none" }}>
        <Component onUpdate={onUpdate} input={input} />
      </div>
      {frame.output ? (
        <DataViewer data={frame.output} onInspect={onInspect} busy={isBusy} />
      ) : isBusy ? (
        <p>解析中 ...</p>
      ) : (
        null
      )}
      {!isActive && (
        <p>
          <button type="button" onClick={() => rollback(ix + 1)}>
            ここまで戻る
          </button>
        </p>
      )}
    </section>
  );
};

const Suggestions = () => (
  suggestions.value.length > 0 ? (
    <section>
      <h3>使えそうなコマンド</h3>
      <table>
        <tbody>
          {suggestions.value.map((suggestion: { reason: string, module: AnalyzerModule }) => (
            <tr key={suggestion.module.label}>
              <td style={{ textAlign: "right" }}>
                <button
                    type="button"
                    onClick={busy.value ? undefined : () => pushAnalyzer(suggestion.module)}
                    disabled={busy.value}>
                  {suggestion.module.label}
                </button>
              </td>
              <td>
                {suggestion.reason}
              </td>
            </tr>
          ))}
        </tbody>
      </table>
    </section>
  ) : (
    null
  )
);

export const App = () => (
  <>
    <AnalyzersList />
    <ImporterSelector />
    {stack.value.map((frame, ix) => (
      <Frame key={frame.id} frame={frame} ix={ix} />
    ))}
    <Suggestions />
  </>
);
