import { signal, computed, type Signal } from "@preact/signals";
import { useMemo } from "preact/hooks";
import { gensym } from "./utils/gensym";
import { analyzerCategories, analyzers } from "./modules/analyzers";
import { encoders } from "./modules/encoders";
import { importers } from "./modules/importers";
import { genInspector } from "./modules/inspector";
import { DataViewer } from "./DataViewer";
import type { MaybeData } from "./datatypes";
import type { AnalyzerModule, StateReporter } from "./modules";

/* ---- STATE */

type StackFrame = {
  // An unique id, generated by "gensym" util.
  id: number,
  // Latest output from the module. Updated by "stateReporter" fn defined later.
  // Note that only the frame on top of the stack can be updated.
  output: MaybeData,
  module: AnalyzerModule,
  reporter: StateReporter,
};

type Suggestion = {
  reason: string,
  module: AnalyzerModule,
};

type AppState = {
  busy: Signal<boolean>,
  stack: Signal<StackFrame[]>,
  suggestions: Signal<Suggestion[]>,
  pushAnalyzer: (module: AnalyzerModule) => void,
  inspect: (ix: number) => void,
  rollback: (n: number) => void,
};

const createAppState = (): AppState => {
  const busy = signal(false);
  const stack = signal<StackFrame[]>([]);

  const _stateReporterForId = (id: number): StateReporter => (state) => {
    const _stack = stack.peek(); // do not subscribe, to avoid infinite loops
    // If the frame is no longer active, do nothing.
    // This may occur when stateReporter is called from an async analyzer.
    if (id === _stack[_stack.length - 1]?.id) {
      busy.value = !!state.busy;
      if (state.output !== undefined) {
        stack.value = [
          ..._stack.slice(0, -1),
          { ..._stack[_stack.length - 1], output: state.output },
        ];
      }
    }
  };

  // List of suggestions for the last output.
  const suggestions = computed<{ reason: string, module: AnalyzerModule }[]>(() => {
    const suspicious = stack.value[stack.value.length - 1]?.output;
    if (suspicious && suspicious.type !== "error") {
      return analyzers.map(analyzer => {
        const reason = analyzer.detect?.(suspicious) ?? null;
        if (reason) {
          return { reason, module: analyzer };
        }
        return null;
      }).filter(suggestion => !!suggestion);
    }
    return [];
  });

  // Initialize an analyzer and push on to the stack.
  const pushAnalyzer = (module: AnalyzerModule) => {
    const _stack = stack.peek(); // do not subscribe, to avoid infinite loops
    const id = gensym();
    busy.value = false;
    stack.value = [
      ..._stack,
      { id, module, reporter: _stateReporterForId(id), output: null },
    ];
  };

  // Inspect a single element in a MultipleData.
  const inspect = (ix: number) => {
    const _stack = stack.peek(); // do not subscribe, to avoid infinite loops
    const id = gensym();
    busy.value = false;
    stack.value = [
      ..._stack,
      { id, module: genInspector(ix), reporter: _stateReporterForId(id), output: null },
    ];
  };

  // Rollback to undo N-th frame (= activate "N-1"-th frame)
  const rollback = (n: number) => {
    const _stack = stack.peek(); // do not subscribe, to avoid infinite loops
    busy.value = false;
    stack.value = _stack.slice(0, n);
  };

  return { busy, stack, suggestions, pushAnalyzer, inspect, rollback };
}

/* ---- UI */

const AnalyzersList = () => (
  <section>
    <details>
      <summary>実装されている変換器・解析器</summary>
      {analyzerCategories.map(category => (
        <div key={category.category}>
          <b>{category.category}</b>
          <div style={{ marginLeft: "16px", fontSize: "smaller" }}>
            {category.analyzers.map((analyzer, ix) => (
              <>
                {ix > 0 ? "、" : ""}
                {analyzer.app ? (
                  <a key={analyzer.label} href={analyzer.app}>{analyzer.label}</a>
                ) : (
                  analyzer.label
                )}
              </>
            ))}
          </div>
        </div>
      ))}
      <div>
        <b>その他</b>
        <div style={{ marginLeft: "16px", fontSize: "smaller" }}>
          <a href="/argtools-jp/apps/filetype">ファイル形式の自動判別</a>
          、<a href="/argtools-jp/anything">条件に一致する単語や地名の特定</a>
        </div>
      </div>
      <div>
        <b>謎解き作成支援</b>
        <div style={{ marginLeft: "16px", fontSize: "smaller" }}>
          {encoders.map((encoder, ix) => (
            <>
              {ix > 0 ? "、" : ""}
              {encoder.app ? (
                <a key={encoder.label} href={encoder.app}>{encoder.label}</a>
              ) : (
                encoder.label
              )}
            </>
          ))}
        </div>
      </div>
    </details>
  </section>
);

const ImporterSelector = ({ state: { stack, pushAnalyzer, rollback } }: {
  state: AppState,
}) => (
  stack.value.length === 0 ? (
    <section>
      <hr />
      <h3>モードを選ぶ：</h3>
      {importers.map(module => (
        <>
          <button
              key={module.label}
              type="button"
              onClick={() => pushAnalyzer(module)}>
            {module.label}
          </button>
          {"　"}
        </>
      ))}
    </section>
  ) : (
    <section>
      <p>
        <button type="button" onClick={() => rollback(0)}>
          最初に戻る
        </button>
      </p>
    </section>
  )
);

const Frame = ({ frame, ix, state: { stack, inspect, busy, rollback } }: {
  frame: StackFrame,
  ix: number,
  state: AppState,
}) => {
  const Component = frame.module.component;

  const input = stack.value[ix - 1]?.output ?? null;

  const isActive = ix === stack.value.length - 1;
  const isBusy = isActive && busy.value;

  const onInspect = isActive ? inspect : undefined;

  return (
    <section key={frame.id}>
      <hr />
      <h3>{frame.module.label}</h3>
      {frame.module.description ?? null}
      {/* render inactive (hidden) components too, to keep their state */}
      <div style={isActive ? { marginBottom: "1em" } : { display: "none" }}>
        <Component onUpdate={frame.reporter} input={input} />
      </div>
      {frame.output ? (
        <DataViewer data={frame.output} onInspect={onInspect} busy={isBusy} />
      ) : isBusy ? (
        <p>解析中 ...</p>
      ) : (
        null
      )}
      {!isActive && (
        <p>
          <button type="button" onClick={() => rollback(ix + 1)}>
            ここまで戻る
          </button>
        </p>
      )}
    </section>
  );
};

const Suggestions = ({ state: { suggestions, busy, pushAnalyzer } }: {
  state: AppState,
}) => (
  suggestions.value.length > 0 ? (
    <section>
      <h3>使えそうなコマンド</h3>
      <table>
        <tbody>
          {suggestions.value.map((suggestion: { reason: string, module: AnalyzerModule }) => (
            <tr key={suggestion.module.label}>
              <td style={{ textAlign: "right" }}>
                <button
                    type="button"
                    onClick={busy.value ? undefined : () => pushAnalyzer(suggestion.module)}
                    disabled={busy.value}>
                  {suggestion.module.label}
                </button>
              </td>
              <td>
                {suggestion.reason}
              </td>
            </tr>
          ))}
        </tbody>
      </table>
    </section>
  ) : (
    null
  )
);

export const App = () => {
  const state = useMemo(createAppState, []);
  const { stack } = state;

  return (
    <>
      <p>各種 ARG、高難易度謎解き、CTF、開けないファイルの解析などにどうぞ。</p>
      <AnalyzersList />
      <ImporterSelector state={state} />
      {stack.value.map((frame, ix) => (
        <Frame key={frame.id} frame={frame} ix={ix} state={state} />
      ))}
      <Suggestions state={state} />
    </>
  );
};
