import type { FunctionComponent } from "preact";
import { useEffect } from "preact/hooks";
import { signal, computed } from "@preact/signals";
import { gensym } from "./utils/gensym";
import { analyzers } from "./analyzers";
import { textData, type Data } from "./datatypes";

// ---- types

export type StateReporter = (state: { busy?: boolean, output?: Data | null }) => void;

export type AnalyzerModule = {
  // An user-friendly description.
  label: string,
  // A path to micro-app.
  app?: string,
  // Check if the module is applicable to a data, and returns an explanation if true.
  // Note that this procedure should return as fast as possible to avoid input lags.
  detect?: (suspicious: Data) => string | null,
  //    input ... The last output from the previous module.
  // onUpdate ... A function to report output.
  component: FunctionComponent<{ onUpdate: StateReporter, input: Data | null }>,
};

export type StackFrame = {
  // An unique id, generated by "gensym" util.
  id: number,
  // Latest output from the module. Updated by "stateReporter" fn defined later.
  // Note that only the frame on top of the stack can be updated.
  output: Data | null,
  module: AnalyzerModule,
};

// ---- state

export const busy = signal(false);
export const stack = signal<StackFrame[]>([]);

export const stateReporterForId = (id: number): StateReporter => (state) => {
  const _stack = stack.peek(); // do not subscribe, to avoid infinite loops
  // If the frame is no longer active, do nothing.
  // This may occur when stateReporter is called from an async analyzer.
  if (id === _stack[_stack.length - 1]?.id) {
    busy.value = !!state.busy;
    if (state.output) {
      stack.value = [
        ..._stack.slice(0, -1),
        { ..._stack[_stack.length - 1], output: state.output },
      ];
    }
  }
};

// List of suggestions for the last output.
export const suggestions = computed<{ reason: string, module: AnalyzerModule }[]>(() => {
  const suspicious = stack.value[stack.value.length - 1]?.output;
  if (suspicious) {
    return analyzers.map(analyzer => {
      const reason = analyzer.detect?.(suspicious) ?? null;
      if (reason) {
        return { reason, module: analyzer };
      }
      return null;
    }).filter(suggestion => !!suggestion);
  }
  return [];
});

// Initialize an analyzer and push on to the stack.
export const pushAnalyzer = (module: AnalyzerModule) => {
  const _stack = stack.peek(); // do not subscribe, to avoid infinite loops
  busy.value = false;
  stack.value = [..._stack, { id: gensym(), module, output: null }];
};

// A special higher-order module to extract an element from a MultipleData.
const _inspectItem = (ix: number): AnalyzerModule => ({
  label: "この項目を精査",
  detect: () => null,
  component: ({ onUpdate, input }: { onUpdate: StateReporter, input: Data | null }) => {
    useEffect(() => {
      if (!input || input.type !== "multiple" || !input.datum[ix]) {
        onUpdate({ output: textData("UNEXPECTED: no inspection target.", "エラー") });
      } else {
        onUpdate({ output: input.datum[ix] });
      }
    }, [onUpdate, ix, input]);
    return null;
  },
})

// An exceptional frame which is not related to any modules.
// This may used to inspect a single element in a set of data.
export const pushInspection = (ix: number) => {
  const _stack = stack.peek(); // do not subscribe, to avoid infinite loops
  busy.value = false;
  stack.value = [..._stack, { id: gensym(), module: _inspectItem(ix), output: null }];
};

// Rollback to undo N-th frame (= activate "N-1"-th frame)
export const rollback = (n: number) => {
  const _stack = stack.peek(); // do not subscribe, to avoid infinite loops
  busy.value = false;
  stack.value = _stack.slice(0, n);
};
