import type { FunctionComponent } from "preact";
import { useEffect, useMemo } from "preact/hooks";
import { signal } from "@preact/signals";
import { gensym } from "./utils/gensym";
import { textData, type Data } from "./datatypes";

// ---- types

export type AnalyzerModule = {
  // An user-friendly description.
  label: string,
  // Check if the module is applicable to a data, and returns an explanation if true.
  // Note that this procedure should return as fast as possible to avoid input lags.
  detect?: (suspicious: Data) => string | null,
  //  id ... An unique id, generated by "gensym" util.
  // src ... The last output from the previous module.
  component: FunctionComponent<{ id: number, input: Data | null }>,
};

export type StackFrame = {
  // An unique id, generated by "gensym" util.
  id: number,
  // Latest output from the module. Updated by "reportOutput" fn defined later.
  output: Data | null,
  module: AnalyzerModule,
};

// ---- state

export const busy = signal(false);
export const stack = signal<StackFrame[]>([]);

// Mark the active module as busy (or not busy).
export const reportBusy = (id: number, value: boolean) => {
  const _stack = stack.peek(); // do not subscribe, to avoid infinite loops
  if (id === _stack[_stack.length - 1]?.id) {
    busy.value = value;
  }
};

// Update the active module's output, and mark as not busy
export const reportOutput = (id: number, output: Data | null, intermediate = false) => {
  const _stack = stack.peek(); // do not subscribe, to avoid infinite loops
  if (id === _stack[_stack.length - 1]?.id) {
    stack.value = [
      ..._stack.slice(0, -1),
      { ..._stack[_stack.length - 1], output },
    ];
    if (!intermediate) {
      busy.value = false;
    }
  }
};

// Initialize an analyzer and push on to the stack.
export const pushAnalyzer = (module: AnalyzerModule) => {
  const _stack = stack.peek(); // do not subscribe, to avoid infinite loops
  busy.value = false;
  stack.value = [..._stack, { id: gensym(), module, output: null }];
};

// A special higher-order module to extract an element from a MultipleData.
const _inspectItem = (ix: number): AnalyzerModule => ({
  label: "この項目を精査",
  detect: () => null,
  component: ({ id, input }: { id: number, input: Data | null }) => {
    useEffect(() => {
      if (!input || input.type !== "multiple" || !input.datum[ix]) {
        reportOutput(id, textData("UNEXPECTED: no inspection target.", "エラー"));
      } else {
        reportOutput(id, input.datum[ix]);
      }
    });
    return null;
  },
})

// An exceptional frame which is not related to any modules.
// This may used to inspect a single element in a set of data.
export const pushInspection = (ix: number) => {
  const _stack = stack.peek(); // do not subscribe, to avoid infinite loops
  busy.value = false;
  stack.value = [..._stack, { id: gensym(), module: _inspectItem(ix), output: null }];
};

// Rollback to undo N-th frame (= activate "N-1"-th frame)
export const rollback = (n: number) => {
  const _stack = stack.peek(); // do not subscribe, to avoid infinite loops
  busy.value = false;
  stack.value = _stack.slice(0, n);
};

// thin wrapper for analyzer modules to handle errors and state management
export const useAnalyzerEffect = (
  id: number,
  cb: () => Data | null,
  deps: any[],
) => {
  // biome-ignore lint/correctness/useExhaustiveDependencies:
  const fn = useMemo(() => cb, deps);
  useEffect(() => {
    reportBusy(id, true);
    try {
      reportOutput(id, fn());
    } catch (e: any) {
      reportOutput(id, textData("message" in e ? e.message : "Unexpected error.", "エラー"));
    }
  }, [id, fn]);
};

// thin wrapper for analyzer modules to handle errors and state management
export const useAsyncAnalyzerEffect = (
  id: number,
  cb: () => Promise<Data | null>,
  deps: any[],
) => {
  // biome-ignore lint/correctness/useExhaustiveDependencies:
  const fn = useMemo(() => cb, deps);
  useEffect(() => {
    reportBusy(id, true);
    fn().then(output => {
      reportOutput(id, output);
    }).catch(e => {
      reportOutput(id, textData("message" in e ? e.message : "Unexpected error.", "エラー"));
    });
  }, [id, fn]);
};
