name: Build

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v3.6.0
      - run: yarn install
      - run: yarn run lint
      - run: yarn run check
      - run: NODE_OPTIONS="--max-old-space-size=8192" yarn run build
      - uses: peaceiris/actions-gh-pages@v3.9.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist/client
  update-sitemap:
    needs: build-and-deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          ref: gh-pages
          fetch-depth: 0
      - uses: cicirello/generate-sitemap@v1
        with:
          base-url-path: "https://zk-phi.github.io/argtools-jp/"
      - run: |
          git config user.name "Github Actions"
          git config user.email "action@github.com"
          git add sitemap.xml
          git commit -m "[bot] Update sitemap.xml"
          git push
