name: Update sitemap.xml

on:
  push:
    branches:
      - gh-pages
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: cicirello/generate-sitemap@v1
        with:
          base-url-path: "https://zk-phi.github.io/argtools-jp/"
      - run: |
          git config user.name "Github Actions"
          git config user.email "action@github.com"
          git add sitemap.xml
          git commit -m "[bot] Update sitemap.xml"
          git push
